package com.pocketai.app
import android.content.ClipData
import android.content.ClipboardManager
import android.content.Context
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.*
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.*
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.text.selection.SelectionContainer
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.unit.dp
import com.pocketai.app.data.*
import kotlinx.coroutines.launch

enum class Page{CHAT,CHATS,MODELS,SETTINGS,PRIVACY}
@Composable fun PocketTheme(content:@Composable()->Unit){MaterialTheme(colorScheme=darkColorScheme(surface=androidx.compose.ui.graphics.Color(0xFF111318),background=androidx.compose.ui.graphics.Color(0xFF0D0F12)),content=content)}
@Composable fun PocketRoot(vm:MainViewModel){val s by vm.state.collectAsState();var page by remember{mutableStateOf(Page.CHAT)};if(!s.settings.onboardingDone&&s.models.isEmpty()){Onboarding(vm){page=Page.MODELS};return};Scaffold(topBar={TopAppBar(title={Column{Text("Pocket AI");Text(s.selectedModel?.name?:"Geen model geselecteerd",style=MaterialTheme.typography.labelSmall)}},actions={IconButton({page=Page.MODELS}){Icon(Icons.Default.Memory,"Models")};IconButton({page=Page.SETTINGS}){Icon(Icons.Default.Settings,"Settings")}})},bottomBar={NavigationBar{listOf(Page.CHAT to Icons.Default.Chat,Page.CHATS to Icons.Default.History,Page.MODELS to Icons.Default.Memory,Page.SETTINGS to Icons.Default.Settings).forEach{(p,i)->NavigationBarItem(page==p,{page=p},{Icon(i,p.name)},label={Text(p.name.lowercase().replaceFirstChar{it.uppercase()})})}}}){pad->Box(Modifier.padding(pad).fillMaxSize()){when(page){Page.CHAT->ChatPage(s,vm);Page.CHATS->ChatsPage(s,vm){page=Page.CHAT};Page.MODELS->ModelsPage(s,vm);Page.SETTINGS->SettingsPage(s,vm){page=Page.PRIVACY};Page.PRIVACY->PrivacyPage()};s.error?.let{Snackbar(Modifier.align(Alignment.BottomCenter).padding(16.dp),action={TextButton(vm::dismissError){Text("OK")}}){Text(it)}}}}}
@Composable fun Onboarding(vm:MainViewModel,onImport:()->Unit){val launcher=rememberLauncherForActivityResult(ActivityResultContracts.OpenDocument()){it?.let(vm::importModel)};Column(Modifier.fillMaxSize().padding(32.dp),verticalArrangement=Arrangement.Center){Icon(Icons.Default.Lock, null,Modifier.size(56.dp));Spacer(Modifier.height(20.dp));Text("Pocket AI",style=MaterialTheme.typography.headlineLarge);Text("Privé AI op je telefoon",style=MaterialTheme.typography.titleMedium);Spacer(Modifier.height(20.dp));Text("Chats en modellen blijven lokaal. Om te beginnen heb je een GGUF-model nodig. Na import is voor normale chats geen internet nodig.");Spacer(Modifier.height(24.dp));Button({launcher.launch(arrayOf("application/octet-stream","*/*"))},Modifier.fillMaxWidth()){Text("Import GGUF model")};TextButton(onImport,Modifier.fillMaxWidth()){Text("Modelbeheer openen")};Text("Modeldownloads zijn in v0.1 bewust niet automatisch: Pocket AI downloadt nooit stilletjes meerdere GB.",style=MaterialTheme.typography.bodySmall)}}
@Composable fun ChatPage(s:UiState,vm:MainViewModel){var input by remember{mutableStateOf("")};val list=rememberLazyListState();LaunchedEffect(s.messages.lastOrNull()?.content){if(s.messages.isNotEmpty())list.scrollToItem(s.messages.lastIndex)};Column(Modifier.fillMaxSize()){if(s.loadedPath==null)AssistChip({s.selectedModel?.let(vm::loadModel)},label={Text(if(s.selectedModel==null)"Selecteer een model" else "Laad ${s.selectedModel.name}")},modifier=Modifier.padding(12.dp));LazyColumn(Modifier.weight(1f),state=list,contentPadding=PaddingValues(12.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){items(s.messages,key={it.id}){MessageBubble(it)}};if(s.generating)LinearProgressIndicator(Modifier.fillMaxWidth());Row(Modifier.padding(10.dp),verticalAlignment=Alignment.Bottom){OutlinedTextField(input,{input=it},Modifier.weight(1f),placeholder={Text("Bericht…")},shape=RoundedCornerShape(24.dp),maxLines=6);Spacer(Modifier.width(8.dp));FilledIconButton(if(s.generating){{vm.stop()}}else{{val t=input;input="";vm.send(t)}},enabled=s.generating||input.isNotBlank()){Icon(if(s.generating)Icons.Default.Stop else Icons.Default.Send,null)}};Row(Modifier.padding(horizontal=12.dp,vertical=4.dp)){TextButton(vm::newChat){Text("Nieuwe chat")};Spacer(Modifier.weight(1f));TextButton(vm::regenerate,enabled=s.messages.any{it.role=="user"}&&!s.generating){Text("Opnieuw genereren")}}}}
@Composable fun MessageBubble(m:Message){val c=LocalContext.current;Column(Modifier.fillMaxWidth(),horizontalAlignment=if(m.role=="user")Alignment.End else Alignment.Start){Surface(shape=RoundedCornerShape(18.dp),tonalElevation=if(m.role=="user")4.dp else 1.dp,modifier=Modifier.fillMaxWidth(if(m.role=="user") .88f else 1f)){Column(Modifier.padding(14.dp)){SelectionContainer{MarkdownLite(m.content)};Row{Spacer(Modifier.weight(1f));IconButton({(c.getSystemService(Context.CLIPBOARD_SERVICE) as ClipboardManager).setPrimaryClip(ClipData.newPlainText("Pocket AI",m.content))}){Icon(Icons.Default.ContentCopy,"Kopiëren",Modifier.size(18.dp))}}}}}}
@Composable fun MarkdownLite(t:String){Column{t.split("\n").forEach{line->when{line.startsWith("### ")->Text(line.drop(4),style=MaterialTheme.typography.titleMedium);line.startsWith("## ")->Text(line.drop(3),style=MaterialTheme.typography.titleLarge);line.startsWith("# ")->Text(line.drop(2),style=MaterialTheme.typography.headlineSmall);line.startsWith("```")->Divider();line.startsWith("    ")->Text(line.trimStart(),fontFamily=FontFamily.Monospace);line.startsWith("- ")->Text("• "+line.drop(2));else->Text(line)}}}}
@Composable fun ChatsPage(s:UiState,vm:MainViewModel,open:()->Unit){LazyColumn(contentPadding=PaddingValues(12.dp)){item{Button(vm::newChat){Text("Nieuwe chat")}};items(s.conversations,key={it.id}){c->ListItem(headlineContent={Text(c.title)},modifier=Modifier.clickable{vm.open(c.id);open()},trailingContent={IconButton({vm.deleteChat(c.id)}){Icon(Icons.Default.Delete,"Verwijderen")}})}}}
@Composable fun ModelsPage(s:UiState,vm:MainViewModel){val pick=rememberLauncherForActivityResult(ActivityResultContracts.OpenDocument()){it?.let(vm::importModel)};Column(Modifier.padding(12.dp)){Button({pick.launch(arrayOf("application/octet-stream","*/*"))},Modifier.fillMaxWidth()){Icon(Icons.Default.Add,null);Text(" Import GGUF model")};Spacer(Modifier.height(8.dp));LazyColumn{items(s.models,key={it.id}){m->Card(Modifier.fillMaxWidth().padding(vertical=5.dp)){Column(Modifier.padding(14.dp)){Text(m.name,style=MaterialTheme.typography.titleMedium);Text(formatBytes(m.sizeBytes));Text(if(s.loadedPath==m.path)"Geladen" else if(m.isSelected)"Geselecteerd" else "Niet geladen");Row{TextButton({vm.selectModel(m.id)}){Text("Selecteer")};TextButton({vm.loadModel(m)}){Text("Laad")};if(s.loadedPath==m.path)TextButton(vm::unload){Text("Ontlaad")};Spacer(Modifier.weight(1f));IconButton({vm.deleteModel(m)}){Icon(Icons.Default.Delete,"Verwijder")}}}}}}}}
fun formatBytes(n:Long):String=when{n>=1L shl 30->"%.2f GB".format(n.toDouble()/(1L shl 30));n>=1L shl 20->"%.1f MB".format(n.toDouble()/(1L shl 20));else->"$n bytes"}
@Composable fun SettingsPage(s:UiState,vm:MainViewModel,privacy:()->Unit){var x by remember(s.settings){mutableStateOf(s.settings)};Column(Modifier.verticalScroll(rememberScrollState()).padding(16.dp)){Text("System prompt");OutlinedTextField(x.systemPrompt,{x=x.copy(systemPrompt=it)},Modifier.fillMaxWidth(),minLines=3);SettingSlider("Temperature",x.temperature,0f..2f){x=x.copy(temperature=it)};SettingSlider("Top-p",x.topP,.05f..1f){x=x.copy(topP=it)};Text("Top-k: ${x.topK}");Slider(x.topK.toFloat(),{x=x.copy(topK=it.toInt())},valueRange=0f..100f);Text("Context: ${x.contextSize}");Slider(x.contextSize.toFloat(),{x=x.copy(contextSize=(it/512).toInt()*512)},valueRange=1024f..8192f);Text("Maximum nieuwe tokens: ${x.maxTokens}");Slider(x.maxTokens.toFloat(),{x=x.copy(maxTokens=(it/128).toInt()*128)},valueRange=128f..4096f);Button({vm.saveSettings(x)},Modifier.fillMaxWidth()){Text("Instellingen opslaan")};OutlinedButton({vm.resetSettings()},Modifier.fillMaxWidth()){Text("Reset naar standaardinstellingen")};TextButton(privacy,Modifier.fillMaxWidth()){Text("Privacy & informatie")};TextButton(vm::clearChats,Modifier.fillMaxWidth()){Text("Alle chats wissen")}}}
@Composable fun SettingSlider(name:String,v:Float,r:ClosedFloatingPointRange<Float>,set:(Float)->Unit){Text("$name: %.2f".format(v));Slider(v,set,valueRange=r)}
@Composable fun PrivacyPage(){Column(Modifier.verticalScroll(rememberScrollState()).padding(20.dp)){Text("Privacy & informatie",style=MaterialTheme.typography.headlineMedium);Spacer(Modifier.height(12.dp));Text("Pocket AI voert normale AI-chat lokaal uit met llama.cpp. Prompts, antwoorden en chatgeschiedenis worden in de appdatabase op dit toestel opgeslagen. Geïmporteerde GGUF-modellen worden naar app-private opslag gekopieerd. Er zijn geen analytics, advertenties of trackers. Cloud-back-up en device-transfer voor appdata zijn uitgeschakeld.\n\nDe INTERNET-permissie is alleen gereserveerd voor een expliciete toekomstige modeldownloadfunctie; chat-inference gebruikt geen netwerk-API. De huidige versie downloadt zelf geen modellen.")}}
